{% set name = "etcd" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/etcd-io/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 499c3adca699199981cd46e1267dccdd4c34bbc111fc9166dc555cbf9ca91918

build:
  number: 0
  script:
    {% for path in [ ".", "./etcdctl" ] %}
    - go install -v {{ path }}
    {% endfor %}

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - etcd --version
    - etcdctl version

about:
  home: https://etcd.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://etcd.io/docs
  dev_url: https://github.com/etcd-io/etcd

extra:
  recipe-maintainers:
    - sodre
