{% set import_path = "github.com/coreos/etcd" %}
{% set version = "3.4.1" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = 'src' + os.sep+ import_path.replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ import_path | replace("coreos", "etcd-io") }}/archive/v{{ version }}.tar.gz
    sha256: 23f2c9536611a5b3ce9e0c047dfc76f18b02db633cc0e86f80d41dad3a8ac948

build:
  number: 0
  skip: True  # [win32]
  script:
    - pushd {{ pkg_src }}
    {% for path in [ ".", "./etcdctl" ] %}
    - go install -v {{ path }}
    {% endfor %}

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - etcd --version
    - etcdctl --version

about:
  home: https://etcd.io
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://etcd.io/docs
  dev_url: https://github.com/etcd-io/etcd

extra:
  recipe-maintainers:
    - sodre
