{% set name = "etcd" %}
{% set version = "3.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coreos/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: bc8a8afdbb85734e38e089de21302e50d240983425694d5ed9d5823b1de35b60  # [not win]

  url: https://github.com/coreos/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}-windows-amd64.zip  # [win]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: a82482fcbe161d4fc2785d6ceb1af9f222b9483a913ecc35b3444e44dc77009c  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
    - git  # [not win]

test:
  commands:
    - etcd --version
    - etcdctl --version

    # Ugly hack because etcd&etcdclt are not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coreos.com/etcd/
  license: Apache-2.0
  license_family: Apache
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://coreos.com/etcd/docs/{{ version }}/index.html
  dev_url: https://github.com/coreos/etcd

extra:
  recipe-maintainers:
    - sodre
