{% set name = "etcd" %}
{% set version = "3.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/etcd-io/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 858f5ad8c830a66f6bd0cd19386deea64d374185b32f40650ba979e0a70b8b97

build:
  number: 0
  script:
    {% for path in [ ".", "./etcdctl" ] %}
    - go install -v {{ path }}
    {% endfor %}

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - etcd --version
    - etcdctl version

about:
  home: https://etcd.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://etcd.io/docs
  dev_url: https://github.com/etcd-io/etcd

extra:
  recipe-maintainers:
    - sodre
