# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XpOHH/6NpAWwnBazhAvvW3kSEfDFJB5kpCgtd3AReZ9Q/LZVeRW4tWG9v0XJYy3TiS4yD94wgnn3d1buKfrMJ7VzT1k0U3xGXBfVRYfcI/PpZj8ftR2n6Zb/o/XsPOjfu7a2eHCBr2pbK3mTJPjn0z250QwaTUDsj8CCtMy9otmRCyec0s70paz9365uYyySPbndfIYIvs0Z7JUSlSsh18WS+y2eXkGDCo9ypCiL5CQft5VEGNpviXjCGd9/TFcbMEKVaCGIkZmWrtxdTyuS/v2M41fr85QDz3Y89XAYTqyfGYEKekC3HNum1/783ecxMVqbEPQSswwgGSDa+tAjoYh+p+/2k9qnZJ5nwXtKWBFSQNDgxeLsf1ndKDYSLmUk2mAW7Sznhlha1O2zYd/tf7NXzZBwIG5RYFAdx5Ujb0TVxzABHXn79BLjOnT0h+hu6+T+rkfCFJu1WsAQjmDJm0MKWc1CVXP39na4ddg5C9JiHTeJLEw/sH9mKEO9nvzqo3JQXWj3hGHLIz5PmriWs5/BPCr4LljBHa5apeVTftxkgVAAFjhNdJ12B0oN5pZIfdkgmaqm4tidnGV2AJBWtWdAZn3teZBESju+euvX2mkAcHPKV+7kNuFVQVsLxQY3k2FHR3uhEpo1BHJB1orhgRuVaP8q/1culEYh5TFEadI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
