travis:
  secure:
    BINSTAR_TOKEN: Lw7Je1G3BbijDmdr6qXsQvtwsa6zU5Ox7ZbJU7WFjuTWbKw4kza6SvpGTYOAfDO/48ROAMRmh783ggEn8FX3ApNsfK2HcmmKqpJ0IEKrgVUNmrl0/h845JtOdElNJ+NWNX/5Bjyvx7nsP8J4iS9QLL3rbEwK78IUcu4S9Y4xjLyI9m7J5igumt/x0Z2Q6exdhSsilGBQPCMNKm57Oo9kOGS1oncBlgw/+llEQVMImmWLykxiKE3yr4XvPgg2lpAGh0qlGbb/aY2WaC1VcwDRmWTAF0tjGHiWK9syO2WMHF0gP8YDAszuzEvC2eMGDUqU3IIB25dH+O+qIwPTAxE3CZe9JpKleSc2otUz3Cm+U5mQYWBXFO7daBvySPgR1bp8p94YDagDyMU1XNOso/TIPrbN2Ycea6mzViYF4yklbz4gIsGbfqFIZyT0XNZPkuEgL7zKTP+wMm6/CLRaayoCbtNCSiKwH3NFpgkpOfNUy9xosC6UX545RSd9nNtdNNR4UoOdYMFauumpPYbIM4/POvL904jSePxZbXnU1NsyUcnoONy3/2lLq13D1YWeXUOyStSt3fuNtd4s9U/AsKVwcCUWS5y2dTHJpwKoGwgJwuW3plXBWo5o7unOPjzHRh72UNGLf0WffEUPdbLyrsCz36C+Frkc/gdn/xKPJMLSsYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
