appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: XpOHH/6NpAWwnBazhAvvW3kSEfDFJB5kpCgtd3AReZ9Q/LZVeRW4tWG9v0XJYy3TiS4yD94wgnn3d1buKfrMJ7VzT1k0U3xGXBfVRYfcI/PpZj8ftR2n6Zb/o/XsPOjfu7a2eHCBr2pbK3mTJPjn0z250QwaTUDsj8CCtMy9otmRCyec0s70paz9365uYyySPbndfIYIvs0Z7JUSlSsh18WS+y2eXkGDCo9ypCiL5CQft5VEGNpviXjCGd9/TFcbMEKVaCGIkZmWrtxdTyuS/v2M41fr85QDz3Y89XAYTqyfGYEKekC3HNum1/783ecxMVqbEPQSswwgGSDa+tAjoYh+p+/2k9qnZJ5nwXtKWBFSQNDgxeLsf1ndKDYSLmUk2mAW7Sznhlha1O2zYd/tf7NXzZBwIG5RYFAdx5Ujb0TVxzABHXn79BLjOnT0h+hu6+T+rkfCFJu1WsAQjmDJm0MKWc1CVXP39na4ddg5C9JiHTeJLEw/sH9mKEO9nvzqo3JQXWj3hGHLIz5PmriWs5/BPCr4LljBHa5apeVTftxkgVAAFjhNdJ12B0oN5pZIfdkgmaqm4tidnGV2AJBWtWdAZn3teZBESju+euvX2mkAcHPKV+7kNuFVQVsLxQY3k2FHR3uhEpo1BHJB1orhgRuVaP8q/1culEYh5TFEadI=}
provider:
  win: azure
bot:
  automerge: true
